# Generated by Django 2.2.9 on 2020-02-27 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=50)),
                ('teamPoints', models.SmallIntegerField()),
                ('defenders', models.ManyToManyField(blank=True, limit_choices_to={'position': 2}, related_name='defenders', to='players.Player')),
                ('forwards', models.ManyToManyField(blank=True, limit_choices_to={'position': 4}, related_name='forwards', to='players.Player')),
                ('goalkeepers', models.ManyToManyField(blank=True, limit_choices_to={'position': 1}, related_name='goalkeepers', to='players.Player')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('midfielders', models.ManyToManyField(blank=True, limit_choices_to={'position': 3}, related_name='midfielders', to='players.Player')),
            ],
        ),
    ]
