# Generated by Django 2.2.9 on 2020-03-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='kit',
            field=models.CharField(default='grey-top', max_length=50),
        ),
    ]
