# Generated by Django 2.2.9 on 2020-03-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.CharField(blank=True, default='https://www.oxfordmail.co.uk/resources/images/10635381.jpg?display=1&htype=0&type=responsive-gallery', max_length=500),
        ),
    ]
