# Generated by Django 2.2.9 on 2020-02-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='teams',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=50)),
                ('teamPoints', models.SmallIntegerField()),
                ('league', models.ManyToManyField(blank=True, related_name='teams', to='leagues.League')),
            ],
        ),
    ]
