# Generated by Django 2.2.9 on 2020-02-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('leagues', '0002_auto_20200228_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='leagues', to='teams.Team'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
